DROP TABLE IF EXISTS USERS;
 
CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  mobile VARCHAR(250) NOT NULL,
  enddate VARCHAR NOT NULL,
  age INT NOT NULL
);